source 'https://github.com/CocoaPods/Specs.git'

target 'DraugiemSDK', :exclusive => true do
  pod "DraugiemSDK", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DraugiemSDK", :path => "../"

  
end
